# This rule is not used by the project goat-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to animals.baaaa.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: goat-operator
    app.kubernetes.io/managed-by: kustomize
  name: goat-viewer-role
rules:
- apiGroups:
  - animals.baaaa.io
  resources:
  - goats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - animals.baaaa.io
  resources:
  - goats/status
  verbs:
  - get
