---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - animals.baaaa.io
  resources:
  - goats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - animals.baaaa.io
  resources:
  - goats/finalizers
  verbs:
  - update
- apiGroups:
  - animals.baaaa.io
  resources:
  - goats/status
  verbs:
  - get
  - patch
  - update
